---
abstract: 'a mouse based logic game'
author:
  - 'Tobias Leich <froggs@cpan.org>'
build_requires: {}
configure_requires:
  Module::Build: 0.38
dynamic_config: 1
generated_by: 'Module::Build version 0.38, CPAN::Meta::Converter version 2.110930'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Games-Puzzle-BubbleBreaker
provides:
  Games::Puzzle::BubbleBreaker:
    file: lib/Games/Puzzle/BubbleBreaker.pm
    version: 0.01
requires:
  File::ShareDir: 1.00
  File::Spec: 0
  SDL: 2.532
  Time::HiRes: 0
resources:
  license: http://dev.perl.org/licenses/
  repository: http://github.com/FROGGS/Games-BubbleBreaker
version: 0.01
